
name: NPC
version: "${pom.version}"
api: ["1.0.7"]
main: idk.random.npc.NPC

commands:
  npc:
    description: NPC command
    usage: "/npc"
    permission: npc
permissions:
  npc:
    description: "NPC permission"
    default: op
