
name: NPC
version: "1.0"
api: ["1.0.0"]
main: idk.random.npc.NPC

commands:
  npc:
    description: NPC command
    usage: "/npc"
    permission: npc
permissions:
  npc:
    description: ""
    default: OP
