name: NPC
version: "${pom.version}"
api: ["1.0.9"]
main: idk.plugin.npc.Loader
author: PetteriM1

authors:
  - PetteriM1
  - C1oky

loadbefore:
  - FormAPI

softdepend:
  - FormAPI

permissions:
  npc.use:
    default: op